"""empty message

Revision ID: 701bb2880cfb
Revises: 62433ad6f962
Create Date: 2018-02-27 00:44:36.321054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701bb2880cfb'
down_revision = '62433ad6f962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
